schema {
  query: MyAPIQuery
  mutation: MyAPIMutation
}

type CreateRoomResult {
  room: RoomType!
  player: PlayerType!
}

"""Date with time (isoformat)"""
scalar DateTime

type Film {
  id: String!
  title: String!
  director: String!
}

type FilmList {
  films: [Film!]!
}

type MyAPIMutation {
  createRoom(nickname: String!): CreateRoomResult!
}

type MyAPIQuery {
  allFilms: FilmList!
  ping(message: String!): String!
}

type PlayerType {
  id: ID!
  nickname: String!
  isCreator: Boolean!
  joinedAt: DateTime!
}

enum RoomStatus {
  WAITING
  ACTIVE
  FINISHED
}

type RoomType {
  id: ID!
  code: String!
  gameType: String!
  status: RoomStatus!
  createdAt: DateTime!
  creator: PlayerType!
}
