schema {
  query: MyAPIQuery
  mutation: MyAPIMutation
}

type CreateRoomResult {
  room: RoomType!
  player: PlayerType!
}

"""Date with time (isoformat)"""
scalar DateTime

type JoinRoomResult {
  success: Boolean!
  error: String
  room: RoomType
  player: PlayerType
}

type MyAPIMutation {
  createRoom(nickname: String!): CreateRoomResult!
  joinRoom(code: String!, nickname: String!): JoinRoomResult!
  startGame(code: String!): StartGameResult!
}

type MyAPIQuery {
  ping(message: String!): String!
  roomByCode(code: String!): RoomType
}

type PlayerType {
  id: ID!
  nickname: String!
  isCreator: Boolean!
  joinedAt: DateTime!
}

enum RoomStatus {
  WAITING
  ACTIVE
  FINISHED
}

type RoomType {
  id: ID!
  code: String!
  gameType: String!
  status: RoomStatus!
  createdAt: DateTime!
  creator: PlayerType!
  players: [PlayerType!]!
}

type StartGameResult {
  success: Boolean!
  error: String
  room: RoomType
}
