[project]
name = "react_python_graphql_example"
version = "0.1.0"
description = "React + Python GraphQL Example"
authors = [
    {name = "Matt Guo", email = "matt@mattguo.com"}
]
requires-python = ">=3.12"
dependencies = [
    "strawberry-graphql[fastapi,cli]>=0.219.0",
    "uvicorn>=0.27.0",
    "fastapi>=0.109.0",
    "sqlalchemy>=2.0.0",
]
